### ISSUE TITLE
下拉距离过大的话，交互会卡死不动

### ISSUE THREAD

**Issue by NoFearInMyHeart** [HuolalaTech/react-pull-to-refreshify#1]
![image](https://github.com/HuolalaTech/react-pull-to-refreshify/assets/29700967/ea9ec8bc-a2f3-4862-9694-dabc32e030ef)

**Comment by liaoliao666** [comment]
这个库是面向移动端设计的，pc 和 mobile 的实现有所不同，移动端不会出现这个问题。
